pipeline {
    agent any

    environment {
        TF_VAR_file = 'terraform.tfvars'
    }

    stages {
        stage('Clone Repo') {
            steps {
                checkout scm
            }
        }

        stage('Terraform Init') {
            steps {
                dir('terraform') {
                    withEnv(["GOOGLE_APPLICATION_CREDENTIALS=/tmp/credentials.json"]) {
                    sh 'cp /tmp/credentials.json credentials.json'
                    sh 'terraform init'
                    }
                }
            }
        }


        stage('Terraform Plan') {
            steps {
                dir('terraform') {
                    sh 'terraform plan -var-file=${TF_VAR_file}'
                }
            }
        }

        stage('Approve Apply?') {
            steps {
                input message: 'Do you want to apply the changes?', ok: 'Yes, apply'
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('terraform') {
                    sh 'terraform apply -auto-approve -var-file=${TF_VAR_file}'
                }
            }
        }
    }

    post {
        success {
            echo 'Terraform pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
