pipeline {
    agent any

    environment {
        TF_VAR_file = 'terraform.tfvars'
    }

    stages {
        stage('Clone Repo') {
            steps {
                checkout scm
            }
        }

        stage('Terraform Init & Plan') {
            steps {
                withCredentials([file(credentialsId: 'gcp-creds', variable: 'GOOGLE_CREDENTIALS')]) {
                    dir('terraform') {
                        sh '''
                            cp $GOOGLE_CREDENTIALS credentials.json
                            terraform init
                            terraform plan -var-file=${TF_VAR_file} -out=tfplan
                            terraform show tfplan
                        '''
                    }
                }
            }
        }

        stage('Approve Apply?') {
            steps {
                input message: 'Do you want to apply the changes?', ok: 'Yes, apply'
            }
        }

        stage('Terraform Apply') {
            steps {
                withCredentials([file(credentialsId: 'gcp-creds', variable: 'GOOGLE_CREDENTIALS')]) {
                    dir('terraform') {
                        sh '''
                            cp $GOOGLE_CREDENTIALS credentials.json
                            terraform apply tfplan
                        '''
                    }
                }
            }
        }
    }

    post {
        failure {
            echo 'Pipeline failed!'
        }
        success {
            echo 'Terraform pipeline completed successfully!'
        }
    }
}
